# [SETUP] 
connect to DuckDB

In [1]:
# Load the extension
%load_ext sql

In [2]:
# Connect to DuckDB
%sql duckdb:///tpch.db

Connecting to 'duckdb:///tpch.db'

In [3]:
%config SqlMagic.displaylimit = 100

In [4]:
%%sql
-- Run a simple show tables
SELECT
  table_name
FROM
  information_schema.tables
WHERE
  table_schema = 'main'

Running query in 'duckdb:///tpch.db'

+------------+
| table_name |
+------------+
|  customer  |
|  lineitem  |
|   nation   |
|   orders   |
|    part    |
|  partsupp  |
|   region   |
|  supplier  |
+------------+

### [Exercise] 

Calculate the money lost due to discounts. Use lineitem to get the price of items (without discounts) that are part of an order and compare it to the order.

**Time limit during live workshop: 10 min**

**Hint**: Figure out the grain that the comparison need to be made in. Think in steps i.e. get the price of all the items in an order without discounts and then compare it to the orders data whose `totalprice` has been computed with discounts.

Here are the schemas of `orders` and `lineitem` tables.

![Orders table](./images/orders.png)


![lineitem table](./images/lineitem.png)

In [5]:
%%sql
-- your code here
WITH nodiscount_price AS (
    SELECT
        l_orderkey,
        SUM(l_extendedprice) AS l_nodiscountprice
    FROM
        lineitem
    GROUP BY
        l_orderkey
)
SELECT
    o_orderkey,
    o_totalprice,
    l_nodiscountprice,
    l_nodiscountprice - o_totalprice AS lostmoney
FROM
    orders AS o
INNER JOIN
    nodiscount_price AS l ON o.o_orderkey = l.l_orderkey
ORDER BY
    o_orderkey;

Running query in 'duckdb:///tpch.db'

+------------+--------------+-------------------+-----------+
| o_orderkey | o_totalprice | l_nodiscountprice | lostmoney |
+------------+--------------+-------------------+-----------+
|     1      |  173665.47   |     181861.27     |  8195.80  |
|     2      |   46929.18   |      44694.46     |  -2234.72 |
|     3      |  193846.25   |     205084.32     |  11238.07 |
|     4      |   32151.78   |      30690.90     |  -1460.88 |
|     5      |  144659.20   |     147828.97     |  3169.77  |
|     6      |   58749.59   |      61998.31     |  3248.72  |
|     7      |  252004.18   |     262131.32     |  10127.14 |
|     32     |  208660.75   |     208845.62     |   184.87  |
|     33     |  163243.98   |     171022.16     |  7778.18  |
|     34     |   58949.67   |      58110.94     |  -838.73  |
|     35     |  253724.56   |     256151.46     |  2426.90  |
|     36     |   68289.96   |      75043.92     |  6753.96  |
|     37     |  206680.66   |     210731.32     |  4050.66  |
|     38     |   82500.05   |      84252.52     |  1752.47  |
|     39     |  341734.47   |     346105.55     |  4371.08  |
|     64     |   39414.99   |      40675.95     |  1260.96  |
|     65     |  110643.60   |     109426.74     |  -1216.86 |
|     66     |  103740.67   |      99188.09     |  -4552.58 |
|     67     |  169405.01   |     169900.97     |   495.96  |
|     68     |  330793.52   |     329849.83     |  -943.69  |
|     69     |  197689.49   |     200470.72     |  2781.23  |
|     70     |  113534.42   |     115503.90     |  1969.48  |
|     71     |  276992.74   |     276545.62     |  -447.12  |
|     96     |   68989.90   |      68040.31     |  -949.59  |
|     97     |  110512.84   |     107460.94     |  -3051.90 |
|     98     |   69168.33   |      69708.22     |   539.89  |
|     99     |  112126.95   |     115303.14     |  3176.19  |
|    100     |  187782.63   |     187048.99     |  -733.64  |
|    101     |  124906.11   |     131494.52     |  6588.41  |
|    102     |  164529.10   |     166723.74     |  2194.64  |
|    103     |  126990.79   |     121662.97     |  -5327.82 |
|    128     |   66195.16   |      69723.16     |  3528.00  |
|    129     |  261013.14   |     267426.80     |  6413.66  |
|    130     |  189484.12   |     192007.08     |  2522.96  |
|    131     |  130464.09   |     135165.08     |  4700.99  |
|    132     |  144947.21   |     142009.03     |  -2938.18 |
|    133     |  114663.57   |     114966.35     |   302.78  |
|    134     |  200354.30   |     203139.58     |  2785.28  |
|    135     |  213713.99   |     210965.17     |  -2748.82 |
|    160     |  124132.06   |     125299.16     |  1167.10  |
|    161     |   34439.93   |      34443.39     |    3.46   |
|    162     |   2726.45    |      2754.56      |   28.11   |
|    163     |  202379.28   |     199496.87     |  -2882.41 |
|    164     |  301925.76   |     311877.18     |  9951.42  |
|    165     |  188023.67   |     189098.44     |  1074.77  |
|    166     |  154451.92   |     162671.05     |  8219.13  |
|    167     |   71124.35   |      76737.61     |  5613.26  |
|    192     |  167668.42   |     168263.73     |   595.31  |
|    193     |   88699.17   |      87847.93     |  -851.24  |
|    194     |  176707.84   |     176806.72     |   98.88   |
|    195     |  191542.31   |     192115.98     |   573.67  |
|    196     |   47095.31   |      47081.70     |   -13.61  |
|    197     |  163700.57   |     167628.42     |  3927.85  |
|    198     |  176189.31   |     182366.43     |  6177.12  |
|    199     |  112986.49   |     116163.20     |  3176.71  |
|    224     |  259960.36   |     262360.25     |  2399.89  |
|    225     |  220441.09   |     223405.55     |  2964.46  |
|    226     |  313134.62   |     330498.23     |  17363.61 |
|    227     |   54880.58   |      54832.67     |   -47.91  |
|    228     |   2749.87    |      2829.09      |   79.22   |
|    229     |  213076.69   |     216841.33     |  3764.64  |
|    230     |  171318.37   |     179781.08     |  8462.71  |
|    231     |  191808.17   |     198703.26     |  6895.09  |
|    256     |  130775.45   |     134867.61     |  4092.16  |
|    257     |   8649.81    |      8926.54      |   276.73  |
|    258     |  294182.42   |     302425.64     |  8243.22  |
|    259     |  123298.34   |     125930.11     |  2631.77  |
|    260     |  272353.52   |     268241.81     |  -4111.71 |
|    261     |  319306.86   |     313949.55     |  -5357.31 |
|    262     |  143146.21   |     141813.48     |  -1332.73 |
|    263     |  149369.68   |     152015.57     |  2645.89  |
|    288     |  266047.60   |     270939.53     |  4891.93  |
|    289     |  211162.52   |     211045.64     |  -116.88  |
|    290     |   99019.42   |      97414.51     |  -1604.91 |
|    291     |  108550.11   |     114097.75     |  5547.64  |
|    292     |   40637.14   |      42874.24     |  2237.10  |
|    293     |   58638.09   |      59277.22     |   639.13  |
|    294     |   49457.90   |      48968.22     |  -489.68  |
|    295     |  130843.69   |     131957.70     |  1114.01  |
|    320     |   53743.60   |      55834.25     |  2090.65  |
|    321     |   86823.16   |      85995.14     |  -828.02  |
|    322     |  205623.50   |     204368.44     |  -1255.06 |
|    323     |  119432.07   |     120850.82     |  1418.75  |
|    324     |   38451.38   |      40936.22     |  2484.84  |
|    325     |  125113.94   |     128750.81     |  3636.87  |
|    326     |  327413.14   |     324848.29     |  -2564.85 |
|    327     |   38488.56   |      39654.39     |  1165.83  |
|    352     |   28648.47   |      29337.92     |   689.45  |
|    353     |  249710.43   |     247576.01     |  -2134.42 |
|    354     |  217160.72   |     218599.53     |  1438.81  |
|    355     |   99516.75   |     103228.68     |  3711.93  |
|    356     |  209439.04   |     212034.85     |  2595.81  |
|    357     |  157411.61   |     158350.40     |   938.79  |
|    358     |  354132.39   |     362233.94     |  8101.55  |
|    359     |  239998.53   |     235597.87     |  -4400.66 |
|    384     |  166753.71   |     170734.03     |  3980.32  |
|    385     |   54948.26   |      55576.00     |   627.74  |
|    386     |  110216.57   |     115406.48     |  5189.91  |
|    387     |  204546.39   |     214394.26     |  9847.87  |
|    388     |  198800.71   |     206414.78     |  7614.07  |
+------------+--------------+-------------------+-----------+
Truncated to displaylimit of 100.